stages:
  - build
  - deploy
  - test

variables:
  APP_DIR: "/home/admin/app"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

before_script:
  - echo "$ec2_ssh_key" > deploy_key && chmod 600 deploy_key

build_preprod: 
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy_preprod:
  stage: deploy
  script:
    - scp -i deploy_key -r dist/* $ec2_user@$ec2_ip_preprod:$APP_DIR
    - ssh -i deploy_key $ec2_user@$ec2_ip_preprod <<EOF
        cd $APP_DIR
        pm2 restart all || pm2 start "npm start" --name "morningnews"
      EOF
  only:
    - main

build_prod: 
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - production

deploy_prod:
  stage: deploy
  script:
    - scp -i deploy_key -r dist/* $ec2_user@$ec2_ip:$APP_DIR
    - ssh -i deploy_key $ec2_user@$ec2_ip <<EOF
        cd $APP_DIR
        pm2 restart all || pm2 start "npm start" --name "morningnews"
      EOF
  only:
    - production

test_cypress:
  stage: test
  image: 
    name: cypress/browsers:latest
    entrypoint: [""]
  before_script:
  - echo "Installation des dépendances"
  - npm install
  - npm run build
  - npm install cypress --save-dev
  - npm start &
  script:
    - echo "Lancement des tests Cypress"
    - npx cypress run --headless --config-file cypress.config.js --browser electron --spec "cypress/e2e/testfront.cy.js"
  only:
    - devloppeur

test_sonarcloud:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - echo "Sonar Scanner en cours"
    - sonar-scanner -Dsonar.branch.name=$CI_COMMIT_BRANCH

  only:
    - devloppeur


