services:
  app:
    image: phuulia/morningnews-frontend-lacapsule:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
    container_name: frontend_morningnews
    environment:
      - CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH}
      - CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
    ports:
      - "3000:3000"

  reverse-proxy:
    image: nginx:latest
    container_name: nginx_morningnews_proxy
    ports:
      - "443:443"
      - "80:80"